version: '3.8'

services:
  ngrok:
    image: ngrok/ngrok
    entrypoint: ngrok --authtoken 2Ca0ixepvwNtwFtKzQncfKE4oUC_28FZSbsRRp8snSX19UDai http http://127.0.0.1:8080
    restart: always
    ports:
      - 6379:6379

  telebot:
    build: .
    env_file: ./.env
    entrypoint: python3 aio_ex.py 
    restart: always
    ports: 
      - 5432:5432
    depends_on:
      - ngrok

 
volumes:
  telebot: 
    driver: local
